server:
  port: 7101
eureka:
  instance:
    hostname: eureka7101.com #eureka服务端的实例名称
  client:
    register-with-eureka: false  # false表示不向注册中心注册自己
    fetch-registry: false  #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # http://${eureka.instance.hostname}:${server.port}/eureka/  # 设置与Eureka Server 交互的地址查询服务和注册服务
      defaultZone: http://eureka7002.com:7102/eureka/,http://eureka7003.com:7103/eureka/

